### ISSUE TITLE
Handle field_type of `list_string`

### ISSUE THREAD

**Issue by baumanno** [kaiamann/wisski_py#1]
Thanks for your valuable work on this API-wrapper!

We've been running into issues with one of our pathbuilders that is referencing a field of type `list_string`. The idea is that only a predefined set of values should be allowed for this item (which is what `list_string` does nicely).

This wrapper doesn't handle `list_string` currently, so I've tried patching up the following: 

https://github.com/baumanno/wisski_py/blob/15a04bebdf948738b782cba5da4e7a2143a55cd2/src/wisski/api.py#L932-L935

Two issues:
a) is this enough to get `list_string` working? We would need to add the inverse direction in `deserialize`, but in theory...?
b) is it possible in any way to automatically add the API-transmitted value to the list of allowed string-values? E.g. by creating them as new entities associated with the "list container"

**Comment by kaiamann** [comment]
To adress your questions:
a) I don't really know how the API handles `list_string` at the moment, but I would guess that `list_string` is internally handled like any other normal `text (plain)` field. So in theory your fix should be enough (+ accompanying code in `deserialize`). Did you by any chance look at the json that comes back from the Drupal side and the field value for the `list_string` field?

EDIT: The issue was that I put an empty dict as default value for not explicitly stated field types in `format_value`. I've set the new default to `{"value": value}` in the latest commit 21e3d7b. I hope that fixes it. The corresponding function in the inverse direction `get_value` already assumes that `{"value": value}`  is the default format so that direction should not need any adjustments.

b) I would guess that it is generally possible to add new values to the list of allowed values. However I would like to avoid doing this automatically on the transmission of actual data, since the whole point of the `list_string` is to validate the "incoming" values against a set of allowed values. 
I think the proper way of doing something like this would be to add a new set of API routes that allow setting/adjusting Field/Bundle settings in general, but that would be a bigger project to tackle.
